name: dicom_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - opencv
  - matplotlib
  - scikit-image
  - numpy
  - pydicom
  - ipykernel