# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYY3iNwfPtohZv1F7ODqjk2hc0VM4pGk
"""

import webview
import os
import json
from nodulereconstruction_v0_4 import Nodule_Reconstruction

# This function will be called from JS
class Api:
    def run_pipeline(self, dcm_path, json_path):
        try:
            recon = Nodule_Reconstruction(dcm_path, json_path)
            volume = recon.build_3d_Mask()
            recon.visualize_3d_Mask(volume)
            recon.compute_max_nodule_extent(volume)
            return "Done"
        except Exception as e:
            return f"Error: {str(e)}"

if __name__ == '__main__':
    api = Api()
    webview.create_window("Nodule Viewer", "Demonstrator.html", js_api=api)
    webview.start()